# MEMORY.md（Shino's Bolg）

> Generated by `ai-workflow-bootstrap` on 2026-03-18.
> 目标：将项目协作记忆压缩为前 200 行高信噪比简报。

## 0) 维护约定（前 200 行工作区）

- 前 200 行只保留对实现决策有影响的信息。
- 每次出现改动后立即更新：关键决策 / 风险 / 当前任务 / 最近更新（任务收尾再兜底一次）。
- 超出预算时，把历史细节下沉到文末 Archive。
- 日期格式统一：`YYYY-MM-DD`。

### 结构与预算（总计 ≤ 200 行）

| 区块 | 预算 |
| --- | --- |
| 1) 项目快照 | ≤ 25 行 |
| 2) 不可违反约束 | ≤ 35 行 |
| 3) 关键决策 | ≤ 55 行 |
| 4) 已踩坑与回归风险 | ≤ 40 行 |
| 5) 当前任务与下一步 | ≤ 35 行 |
| 6) 最近更新记录 | ≤ 10 行 |

---

## 1) 项目快照（预算 ≤ 25 行）

- 项目名：`Shino's Bolg`
- 项目根目录：`/home/shino/Codes/Personal Blog`
- 技术栈：`Frontend: Vite + TypeScript (Vanilla SPA); Backend: Elysia.js placeholder; Content: Markdown`
- 后端存在：`yes`
- 默认质量闸门命令：`cd frontend && bun run typecheck && bun run build`
- 协作文档目录：`docs/ai-workflow/`

## 2) 不可违反约束（预算 ≤ 35 行）

- Markdown 转 HTML 后必须做安全清洗：`DOMPurify.sanitize(...)`。
- Frontmatter 必须强校验：`title/slug/date/tags/summary/status` 六字段缺一不可。
- `slug` 与 `tag` 必须匹配 `^[a-z0-9]+(?:-[a-z0-9]+)*$`。
- 列表页、标签页、归档页只能展示 `status: published`。
- `/posts/:slug` 若文章不存在或为草稿，必须进入 404。
- 所有带模糊扩散的 `box-shadow` 必须限制在文章卡片同级（`3px/4px` 扩散级别）；禁止再引入 `8px+` 扩散阴影。
- Stop Hooks 采用中等自动化：自动检查 + 报告，不无限重试。
- 默认收尾输出三段：`Checks Run / Findings / Next Action`。
- 每次修改后必须自动执行 memory sync；任务收尾必须再做一次兜底 sync。
- 命中 `frontend/` 改动的任务，进入实现前默认执行技能链：`frontend-design -> harden -> polish`。
- 若用户显式点名其他 skill，以用户指定优先；默认链不强行追加。

## 3) 关键决策（预算 ≤ 55 行）

- 决策：协作流程采用 Codex 工作流约定版。
- 决策：初始化模板来自 `ai-workflow-bootstrap`。
- 决策：质量闸门主命令为 `cd frontend && bun run typecheck && bun run build`。
- 决策：项目正式名称固定为 `Shino's Bolg`，文档中沿用该拼写，不自动更正为 `Blog`。
- 决策：前端继续使用 Vanilla TS，不迁移框架。
- 决策：页面主体采用单栏极简布局（全局 App Shell + 路由页内容区）。
- 决策：Markdown 渲染栈固定为 `marked + DOMPurify`。
- 决策：内容源使用 `import.meta.glob(...?raw)` 直接读取本地 Markdown。
- 决策：`/tags` 升级为「标签云 + 本页展开文章面板」，主交互不再是直接跳转。
- 决策：标签页 Delight 风格采用蓝青+中性色、1~5 级尺寸和低位移动效；保留 `prefers-reduced-motion` 兜底。
- 决策：首版生产部署采用 1Panel 静态站点，仅发布 `frontend/dist`，后端继续占位不启用。
- 决策：发布流程固定为“本地构建 -> 打包 dist -> 上传 1Panel 根目录 -> Nginx SPA 回退”。
- 决策：ICP备案与公安备案信息集中在 `frontend/src/config/site.ts` 统一维护。
- 决策：备案展示策略为“ICP 必显 + 公安可选”；当公安备案号存在时自动显示双备案。
- 决策：文章卡片动效统一为一套编排（首页/文章页/标签页/标签详情/标签面板），按视觉顺序上到下依次浮现。
- 决策：首页卡片改为“上到下依次 + 从左侧弹入”（`28px` + `520ms`），并将同款效果应用到左侧资料名片与个人信息展示板。
- 决策：workflow 升级为“每次修改后自动 memory sync + 收尾兜底 sync”。
- 决策：新增前端任务自动技能路由，默认链固定为 `frontend-design -> harden -> polish`。
- 决策：`/posts` 新增右侧“主题分类卡片”，主题数据源为 frontmatter `theme`，与 `tags` 完全独立。
- 决策：`/about` 内容源改为 `frontend/src/content/about.md`，并通过 `frontend/src/data/about.ts` 统一做解析与视图模型转换。
- 决策：`/about` 采用“平铺无卡片 + 静态虚线（横向分节 + 中轴竖线）+ 920px 内容宽度”设计，不引入 TOC 与更新时间展示。
- 决策：前端预留 `GET /api/about -> { markdown: string }` 契约；进入 `/about` 时尝试拉取 API，失败自动回退本地 markdown，并在路由切换时中止请求。
- 决策：2026-03-26 审计优先级锁定为“视觉一致性优先”，首焦点为标签体系（`tag-list` / `tag-bubble` / `tag-detail-badge`）边框语言统一。
- 决策：前端样式整改执行顺序锁定为 `normalize -> harden -> optimize`。
- 决策：`/tags` 展开面板移除预渲染 template，改为运行时按需渲染 `renderPostList(getPostsByTag(tag))` 并做缓存复用。
- 决策：`frontend/src/styles/global.css` 改为样式 manifest，按 `tokens -> base -> layout -> content -> posts -> motion` 顺序聚合子文件。
- 决策：运行时 CSS 自定义属性读写统一走 `frontend/src/utils/dom-style.ts`，只抽样式 plumbing，不抽象动效算法本身。
- 决策：全局 `card-shadow` 保持全包围 halo 尺寸不变（`0 0 3px / 0 0 4px`），并仅增强 hover/focus 阶段的颜色强度，不放大几何。
- 决策：全站阴影扩散上限统一到文章卡片级（`3px/4px`）；头栏、封面、徽标、控件 halo 仅允许调颜色/透明度，不再放大 blur 几何。
- 决策：全站动效新增“语义 token 层”（route/panel/reveal/feedback），并把 route-enter 与 about delay 常量在 `main.ts` 集中管理，避免多入口节奏漂移。
- 决策：小面积控件点缀色按语义映射落地（`info=淡蓝` / `interactive=淡青` / `highlight=淡金`），仅覆盖边框、浅底、阴影与强调文字，不改正文主色。
- 决策：将小面积点缀进一步收敛为“仅保留蓝色语义”，并移除按钮内部渐变底（`control-surface-*` 改为纯色混合底）。
- 决策：标签体系底色透明化统一走 `tag-fill-*` token（normal/quiet/hover/count），覆盖 `tag-list/tag-chip`、`tag-bubble`、`tag-detail-badge`，激活态保持高辨识度。

## 4) 已踩坑与回归风险（预算 ≤ 40 行）

- 风险：frontmatter 解析逻辑为轻量实现，复杂 YAML 不支持。
  - 防护：content-spec 明确字段格式；非法文件跳过并报错。
- 风险：`build` 可能更新 `dist` 内容造成脏工作区。
  - 防护：保持 `frontend/.gitignore` 忽略 `dist/`，必要时清理已追踪产物。
- 风险：Markdown 原始 HTML 注入导致 XSS。
  - 防护：统一 DOMPurify 清洗，禁止绕过。
- 风险：`/tags` 展开面板改为运行时按需渲染后，若缓存与 ARIA 状态不同步，可能出现内容/状态错乱。
  - 防护：`setupTagCloudInteractions` 集中维护 `panelContentCache`、`aria-pressed/aria-expanded`、Esc 关闭与焦点回退。
- 风险：路由切换时重复绑定标签页事件导致状态错乱。
  - 防护：所有 `/tags` 事件监听都纳入 `setupPageEnhancements` cleanup 生命周期。
- 风险：1Panel 未配置 `try_files $uri $uri/ /index.html` 会导致二级路由刷新 404。
  - 防护：提供 `deploy/nginx/1panel-static-spa-snippet.conf` 并在上线清单强制核查。
- 风险：备案文案与跳转链接不一致会影响公安联网验证。
  - 防护：上线前在 `frontend/src/config/site.ts` 核对真实编号并二次构建上传。
- 风险：高频自动 memory sync 可能引入低价值噪声，挤占前 200 行预算。
  - 防护：仅记录决策/风险/下一步变化；细节下沉 Archive，最近更新保持 10 行内。
- 风险：对所有 frontend 改动统一套用设计链，可能在纯逻辑改动中造成过度设计。
  - 防护：显式约束“用户点名 skill 优先”，并在任务计划中可按目标裁剪技能范围。
- 风险：`theme` 为人工维护字段，未填写文章不会进入主题统计，可能导致主题卡片计数认知偏差。
  - 防护：在卡片文案说明 `theme` 需手工配置；筛选后可用“返回全部文章”恢复全量视图。
- 风险：`/api/about` 暂未落地时，前端若强依赖接口会导致关于页空白。
  - 防护：页面首屏始终使用本地 markdown，同步请求 API 仅做覆盖更新；失败时保留本地渲染结果。
- 风险：标签组件边框/圆角/状态样式分叉，可能导致标签体系视觉不一致并持续回归。
  - 防护：在进入修复前统一标签 token 与组件规范，并优先覆盖 `tag-list` / `tag-bubble` / `tag-detail-badge`。
- 风险：多处交互目标 < 44px，移动端触达体验存在可用性回归风险。
  - 防护：修复阶段按页面统一最小触达尺寸基线，并把标签区和导航区列为首批验收点。
- 风险：标签云筛选状态 ARIA 不完整，存在辅助技术状态传达不足风险。
  - 防护：修复阶段补齐 `aria-pressed/aria-expanded/aria-controls` 与焦点回退策略并做键盘流检查。
- 风险：Markdown eager 全量解析在内容增长后会放大首屏性能压力。
  - 防护：规划 summary/detail 分层与按需解析策略，避免列表页承担正文解析成本。
- 风险：样式拆分后若导入顺序或归属判断错误，容易出现跨文件 cascade 回归。
  - 防护：固定 `global.css` manifest 顺序，并在 `frontend/src/styles/README.md` 记录文件职责与 token/recipe 使用边界。
- 风险：只增强 hover/focus 颜色强度后，若权重过高，激活态可能显得过亮，和 base 的层级对比过大。
  - 防护：优先回归 `/posts`、`/archive`、`/friends`、`/tags`；若 hover 过跳，只回退 hover token 的 `color-mix` 权重，不改 halo 尺寸。
- 风险：新增淡蓝/淡青/淡金后，dark mode 下部分微控件可能出现“亮度感知过高”导致抢眼。
  - 防护：统一走语义 token（`accent-*-soft/text/halo`）并先回归导航、TOC、排序/回顶/复制按钮；必要时只回退 dark token 权重。
- 风险：标签透明度下调后，浅色背景下小字号 tag-count 可能出现对比度不足。
  - 防护：优先回归 `/posts`、`/tags`、`/tags/:tag` 的 count 与 hover 文本；只回调 `tag-fill-count` 和 `tag-text-color`，不改激活态对比。
- 风险：全站阴影扩散压到 `3px/4px` 后，部分 hover/focus 反馈可能显得“轻”。
  - 防护：优先通过颜色权重与透明度增强层级，不回退到更大扩散半径。

## 5) 当前任务与下一步（预算 ≤ 35 行）

- 当前任务：已完成标签体系底色透明化（token + `posts.css`），覆盖文章标签、标签云与标签详情徽标，激活态保持清晰对比。
- 下一步 1：回归 `/posts`、`/tags`、`/tags/:tag` 的 normal/hover/active/focus-visible 四态层级与可读性。
- 下一步 2：重点检查 light/dark 下 tag-count 与主题标签 `tag-chip--theme` 的文本对比度。
- 下一步 3：若观感仍偏重/偏淡，只回调 `tag-fill-*` 百分比，不改交互逻辑与动效参数。

## 6) 最近更新记录（预算 ≤ 10 行）

- 2026-03-31：按“文章卡片级阴影”统一全站模糊扩散，约束为 `3px/4px`；保留 `0 0 0 1px/3px` 与 inset 描边用于可访问性。
- 2026-03-20：新增 1Panel 静态部署脚本/文档/Nginx 片段，并将备案信息改为 `site.ts` 可配置。
- 2026-03-20：备案展示改为“ICP 必显 + 公安可选”，并新增 `frontend-dist-latest.tar.gz` 上传别名。
- 2026-03-20：更新备案信息为“蜀ICP备2026012160号 + 川公网安备51150302000177号”，并重新打包部署产物。
- 2026-03-21：完成统一卡片动效编排；首页卡片、左侧资料名片、个人信息展示板改为上到下依次从左侧弹入。
- 2026-03-21：workflow 改为“每次修改后自动 memory sync + 任务收尾兜底 sync”。
- 2026-03-22：新增前端任务自动技能路由基线（`frontend-design -> harden -> polish`），并约定“用户显式 skill 优先”。
- 2026-03-22：实现 `/posts` 右侧主题分类卡片（frontmatter `theme`），支持点击筛选；安装类三篇已回填 `theme: 安装配置`。
- 2026-03-22：主题卡片移除“全部主题”，改为筛选后显示“返回全部文章”按钮恢复全量列表。
- 2026-03-26：重做 `/about`（平铺无卡片、双色叙事、横向+中轴虚线、920px 版心），并完成内容迁移与 API 契约预留（本地 fallback）。
- 2026-03-26：完成前端样式综合审计（优先视觉一致性），结论 `High 5 / Medium 5 / Low 2`，并锁定标签体系为最高优先级。
- 2026-03-26：完成标签体系整改：统一 tag token/状态语义、补齐 `/tags` ARIA + Esc/焦点回退，并将标签面板改为按需渲染 + 缓存。
- 2026-03-26：将 `global.css` 重构为 manifest，并拆分 `tokens/base/layout/content/posts/motion` 六层；新增 `utils/dom-style.ts` 统一运行时 CSS 变量读写。
- 2026-03-26：首页最新文章卡片日期改为有封面时位于卡片内部、封面左侧， 无封面时回退到内容区右侧；有封面且标签数 > 1 时固定隐藏最后一个候选标签。
- 2026-03-27：保持全包围 halo 为 `0 0 3px / 0 0 4px`，并仅增强 hover/focus shadow token 的颜色强度，让激活高亮更明显。
- 2026-03-27：标签云 `tag-bubble` 基态/激活态阴影切换到文章卡片同款 `card-shadow-cool / card-shadow-cool-hover`，hover 响应语言统一。
- 2026-03-27：标签云 hover/focus 位移从 `1.75x` 全局 hover 距离改为固定 `-6px`，解决实际观感提升不明显的问题。
- 2026-03-27：右侧 `post-theme-card` / `post-toc-card` 补齐桌面端镜像 route-enter 动效，复用左侧名片卡同款时长与 easing，移动端 inline rail 不参与横向滑入。
- 2026-03-29：同步 `PROJECT_STRUCTURE.zh-CN.md` 与 ai-workflow 文档，补齐 `/friends` 路由、`GET /api/about` 契约，并确认项目正式名称为 `Shino's Bolg`。
- 2026-03-29：为 `/about` 增加分层 reveal 动效：分节继续按上到下入场，内部段落 / 左右叙事 / 时间线按阅读顺序递进；hydration 后仅重绑内部 reveal，不重播整页首屏动画。
- 2026-03-29：微调 `/about` 内部动效节奏：拉开左右分栏与 timeline 的 delay，并让桌面端右栏比左栏轻微错后，整体更有呼吸感。
- 2026-03-29：将 `/friends` 友链卡片接入文章卡片同款 reveal 编排，移出普通 scroll reveal，并对齐 hover / focus-within 阴影与位移反馈。
- 2026-03-29：为 `/posts?theme=...` 首屏筛选态的“返回全部文章”按钮补齐与 `post-detail-scroll-top.is-visible` 同语言的 reveal 动效；页内切换主题不重复播放。
- 2026-03-29：将 `/posts?theme=...` 路由首屏卡片动效改为基于最终可见卡片重播；新增 replay 模式，避免隐藏卡片干扰文章页同款入场节奏。
- 2026-03-29：主题卡片按钮页内点击也接入文章卡片 replay；同主题重复点击不重复调度，返回全部文章仍保持不重播全量列表动画。
- 2026-03-29：名片卡相关路由动效改为仅在“无名片卡页面 -> 有名片卡页面”时启用，并将同一开关应用到 route-enter、side-panel pop 与页面级 stagger。
- 2026-03-29：将右侧 `post-theme-card` / `post-toc-card` 从上述路由动效限制中豁免；两者继续保留原有 side-panel pop 路由动效。
- 2026-03-29：再次收窄规则——只有 `.profile-card` 继续使用“无名片卡 -> 有名片卡”特殊路由判定；其它路由动效元素全部恢复原有行为。
- 2026-03-29：将 `.profile-card` 的特殊路由判定再限制为仅桌面端生效；移动端恢复原有路由动效行为。
- 2026-03-29：按 `$bolder + $frontend-design` 完成全站核心动效语义 token 化，并在导航/TOC/排序/回顶/复制等小控件落地淡蓝淡青淡金点缀与统一微光 halo 反馈。
- 2026-03-29：按最新视觉反馈移除淡青/淡金应用，统一收敛为蓝色点缀，并去掉按钮内部渐变效果。
- 2026-03-29：蓝色点缀进一步收敛为“仅头栏保留”，通过在 `site-main/site-footer/浮动控件` 范围覆盖语义 token 回退正文区配色。
- 2026-03-30：实施标签底色透明化：下调 `tag-fill-*` 与标签组件背景浓度，新增 `tag-bubble` 细边框、减轻 `tag-count` 胶囊背景，并同步淡化 `tag-detail-badge/count`。

---

## Archive（200 行外历史区）

> 用于保存低频历史记录，不作为默认上下文注入。
